### ISSUE TITLE
Does not work with Create 0.5c

### ISSUE THREAD

**Issue by itsdinkd** [mrh0/createaddition#311]
As title suggests, create additions breaks when using create 0.5c
```java
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'createaddition'!
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.client.MinecraftClient.redirect$jpl000$catchFabricInit(MinecraftClient:36953)
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:452)
	at net.minecraft.client.main.Main.main(Main:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'com.tterrag.registrate.util.nullness.NonNullConsumer com.simibubi.create.AllMovementBehaviours.addMovementBehaviour(com.simibubi.create.content.contraptions.components.structureMovement.MovementBehaviour)'
	at com.mrh0.createaddition.index.CABlocks.<clinit>(CABlocks.java:75)
	at com.mrh0.createaddition.CreateAddition.onInitialize(CreateAddition.java:47)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 9 more
```

**Comment by xiPakuL** [comment]
duplicate of #287

**Comment by mrh0** [comment]
Fixed in 20220813a.
